name: Build RTL8188EU driver for WSL

on:
  workflow_dispatch:
    inputs:
      # Option A (preferred): paste the exact WSL kernel tag from MS releases
      # e.g. linux-msft-wsl-6.6.87.2  or  linux-msft-wsl-5.15.153.1
      wsl_kernel_tag:
        description: "Exact WSL kernel tag"
        required: false
      # Option B: paste `uname -r` from WSL, we derive the tag (e.g., 6.6.87.2-microsoft-standard-WSL2)
      kernel_release:
        description: "uname -r from WSL (e.g., 6.6.87.2-microsoft-standard-WSL2)"
        required: false
      # Driver repo/branch (defaults to cfg80211-based 8188eu)
      driver_repo:
        description: "Driver repo URL"
        default: "https://github.com/lwfinger/rtl8188eu"
        required: false
      driver_branch:
        description: "Driver branch/tag"
        default: "v5.2.2.4"
        required: false
      module_name:
        description: "Module name label (artifact)"
        default: "8188eu"
        required: false
      retention_days:
        description: "Artifact retention (<= repo/org cap)"
        default: "30"
        required: false

permissions:
  contents: read

concurrency:
  group: wsl8188eu-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve kernel tag
        id: tag
        shell: bash
        run: |
          if [[ -n "${{ github.event.inputs.wsl_kernel_tag }}" ]]; then
            TAG="${{ github.event.inputs.wsl_kernel_tag }}"
          elif [[ -n "${{ github.event.inputs.kernel_release }}" ]]; then
            base="${{ github.event.inputs.kernel_release }}"
            base="${base%%-*}"   # 6.6.87.2-microsoft-standard-WSL2 -> 6.6.87.2
            TAG="linux-msft-wsl-${base}"
          else
            echo "Provide wsl_kernel_tag OR kernel_release." >&2
            exit 1
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex libssl-dev libelf-dev dwarves \
            wget tar xz-utils git ccache

      - name: Fetch WSL kernel source (${ { steps.tag.outputs.tag } })
        run: |
          wget -q "https://github.com/microsoft/WSL2-Linux-Kernel/archive/refs/tags/${{ steps.tag.outputs.tag }}.tar.gz" -O wsl-kernel.tar.gz
          tar -xf wsl-kernel.tar.gz
          echo "KDIR=$(echo WSL2-Linux-Kernel-*)" >> $GITHUB_ENV

      - name: Configure WSL kernel (use config-wsl)
        shell: bash
        run: |
          cd "$KDIR"
          # Prefer arch path; fall back to Microsoft/ path if present in this tag
          if [[ -f arch/x86/configs/config-wsl ]]; then
            cp arch/x86/configs/config-wsl .config
          elif [[ -f Microsoft/config-wsl ]]; then
            cp Microsoft/config-wsl .config
          else
            echo "Could not find config-wsl in this kernel tag." >&2
            exit 1
          fi
          yes "" | make olddefconfig

      - name: Build kernel (to generate Module.symvers)
        # NOTE: modules_prepare does NOT create Module.symvers; we must build.
        # We also set LOCALVERSION to match '-microsoft-standard-WSL2'.
        run: |
          cd "$KDIR"
          make -j"$(nproc)" LOCALVERSION=-microsoft-standard-WSL2 modules

      - name: Clone driver (rtl8188eu)
        run: |
          git clone "${{ github.event.inputs.driver_repo }}" driver
          cd driver
          git fetch --all --tags
          BR="${{ github.event.inputs.driver_branch }}"
          if git rev-parse --verify --quiet "$BR"; then
            git checkout "$BR"
          elif git show-ref --verify --quiet "refs/remotes/origin/$BR"; then
            git checkout -b "$BR" "origin/$BR"
          else
            echo "Branch/tag '$BR' not found in repo." >&2
            exit 1
          fi

      - name: Build module against WSL kernel
        shell: bash
        run: |
          set -e
          export EXTRA_CFLAGS="-Wno-error"
          make -C "$KDIR" M="$GITHUB_WORKSPACE/driver" LOCALVERSION=-microsoft-standard-WSL2 modules

      - name: Collect artifacts
        run: |
          mkdir -p out
          find driver -name "*.ko" -print -exec cp {} out/ \;
          for f in out/*.ko; do
            base=$(basename "$f")
            mv "$f" "out/${base%.ko}-${{ steps.tag.outputs.tag }}.ko"
          done
          ls -la out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.event.inputs.module_name }}-${{ steps.tag.outputs.tag }}"
          path: out/*.ko
          retention-days: ${{ github.event.inputs.retention_days }}
